name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.19.0
  # responsável por inicializar o Firebase no app

  firebase_auth: ^4.4.1
  # gerencia a autenticação com email/senha

  cloud_firestore: ^4.7.0
  # para salvar e recuperar dados do Firestore

  dio: ^5.2.1
  # realiza as requisições HTTP pra consumir a API do JSONPlaceholder

  flutter_bloc: ^8.1.2
  # gerenciador de estado 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  # para criar mocks em testes unitários

flutter:
  uses-material-design: true
